/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as SitemapsBrandsDotxmlRouteImport } from './routes/sitemaps/brands[.]xml'
import { Route as SitemapsCategoriesDotxmlRouteImport } from './routes/sitemaps/categories[.]xml'
import { Route as SitemapsPagesDotxmlRouteImport } from './routes/sitemaps/pages[.]xml'
import { Route as SitemapsProductsDotxmlRouteImport } from './routes/sitemaps/products[.]xml'
import { Route as WishlistShareTokenRouteImport } from './routes/wishlist.$shareToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsBrandsDotxmlRoute = SitemapsBrandsDotxmlRouteImport.update({
  id: '/sitemaps/brands.xml',
  path: '/sitemaps/brands.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsCategoriesDotxmlRoute =
  SitemapsCategoriesDotxmlRouteImport.update({
    id: '/sitemaps/categories.xml',
    path: '/sitemaps/categories.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapsPagesDotxmlRoute = SitemapsPagesDotxmlRouteImport.update({
  id: '/sitemaps/pages.xml',
  path: '/sitemaps/pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsProductsDotxmlRoute = SitemapsProductsDotxmlRouteImport.update({
  id: '/sitemaps/products.xml',
  path: '/sitemaps/products.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistShareTokenRoute = WishlistShareTokenRouteImport.update({
  id: '/wishlist/$shareToken',
  path: '/wishlist/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sitemaps/brands.xml': typeof SitemapsBrandsDotxmlRoute
  '/sitemaps/categories.xml': typeof SitemapsCategoriesDotxmlRoute
  '/sitemaps/pages.xml': typeof SitemapsPagesDotxmlRoute
  '/sitemaps/products.xml': typeof SitemapsProductsDotxmlRoute
  '/wishlist/$shareToken': typeof WishlistShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sitemaps/brands.xml': typeof SitemapsBrandsDotxmlRoute
  '/sitemaps/categories.xml': typeof SitemapsCategoriesDotxmlRoute
  '/sitemaps/pages.xml': typeof SitemapsPagesDotxmlRoute
  '/sitemaps/products.xml': typeof SitemapsProductsDotxmlRoute
  '/wishlist/$shareToken': typeof WishlistShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sitemaps/brands.xml': typeof SitemapsBrandsDotxmlRoute
  '/sitemaps/categories.xml': typeof SitemapsCategoriesDotxmlRoute
  '/sitemaps/pages.xml': typeof SitemapsPagesDotxmlRoute
  '/sitemaps/products.xml': typeof SitemapsProductsDotxmlRoute
  '/wishlist/$shareToken': typeof WishlistShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/offers'
    | '/order-confirmed'
    | '/privacy'
    | '/privacy-policy'
    | '/register'
    | '/returns'
    | '/robots.txt'
    | '/shipping-policy'
    | '/shop'
    | '/sign-in'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/product/$slug'
    | '/sitemaps/brands.xml'
    | '/sitemaps/categories.xml'
    | '/sitemaps/pages.xml'
    | '/sitemaps/products.xml'
    | '/wishlist/$shareToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/offers'
    | '/order-confirmed'
    | '/privacy'
    | '/privacy-policy'
    | '/register'
    | '/returns'
    | '/robots.txt'
    | '/shipping-policy'
    | '/shop'
    | '/sign-in'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/product/$slug'
    | '/sitemaps/brands.xml'
    | '/sitemaps/categories.xml'
    | '/sitemaps/pages.xml'
    | '/sitemaps/products.xml'
    | '/wishlist/$shareToken'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/offers'
    | '/order-confirmed'
    | '/privacy'
    | '/privacy-policy'
    | '/register'
    | '/returns'
    | '/robots.txt'
    | '/shipping-policy'
    | '/shop'
    | '/sign-in'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/product/$slug'
    | '/sitemaps/brands.xml'
    | '/sitemaps/categories.xml'
    | '/sitemaps/pages.xml'
    | '/sitemaps/products.xml'
    | '/wishlist/$shareToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ReturnsRoute: typeof ReturnsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  SitemapsBrandsDotxmlRoute: typeof SitemapsBrandsDotxmlRoute
  SitemapsCategoriesDotxmlRoute: typeof SitemapsCategoriesDotxmlRoute
  SitemapsPagesDotxmlRoute: typeof SitemapsPagesDotxmlRoute
  SitemapsProductsDotxmlRoute: typeof SitemapsProductsDotxmlRoute
  WishlistShareTokenRoute: typeof WishlistShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/brands.xml': {
      id: '/sitemaps/brands.xml'
      path: '/sitemaps/brands.xml'
      fullPath: '/sitemaps/brands.xml'
      preLoaderRoute: typeof SitemapsBrandsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/categories.xml': {
      id: '/sitemaps/categories.xml'
      path: '/sitemaps/categories.xml'
      fullPath: '/sitemaps/categories.xml'
      preLoaderRoute: typeof SitemapsCategoriesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/pages.xml': {
      id: '/sitemaps/pages.xml'
      path: '/sitemaps/pages.xml'
      fullPath: '/sitemaps/pages.xml'
      preLoaderRoute: typeof SitemapsPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/products.xml': {
      id: '/sitemaps/products.xml'
      path: '/sitemaps/products.xml'
      fullPath: '/sitemaps/products.xml'
      preLoaderRoute: typeof SitemapsProductsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/$shareToken': {
      id: '/wishlist/$shareToken'
      path: '/wishlist/$shareToken'
      fullPath: '/wishlist/$shareToken'
      preLoaderRoute: typeof WishlistShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  ReturnsRoute: ReturnsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  SitemapsBrandsDotxmlRoute: SitemapsBrandsDotxmlRoute,
  SitemapsCategoriesDotxmlRoute: SitemapsCategoriesDotxmlRoute,
  SitemapsPagesDotxmlRoute: SitemapsPagesDotxmlRoute,
  SitemapsProductsDotxmlRoute: SitemapsProductsDotxmlRoute,
  WishlistShareTokenRoute: WishlistShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
